version: '3'

services:

  loadbalance:
    image: nginx:alpine
    command: /bin/sh -c "envsubst '$${NGINX_HOST} $${NGINX_SSL_PORT}' < /etc/nginx/conf.d/loadbalance.nginx > /etc/nginx/conf.d/loadbalance.conf && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/config/loadbalance/:/etc/nginx/conf.d/
      - ./nginx/certs/:/etc/nginx/certs/
    environment:
      - NGINX_HOST=localhost
      - NGINX_SSL_PORT=8081
    ports:
      - "8080:80"
      - "8081:443"
    depends_on:
      - app1
      - app2

  app2:
    image: microservice-authors
    environment:
      - DATABASE_HOST=db
    restart: on-failure

    depends_on:
      - db
  app1:
    image: microservice-authors
    environment:
      - DATABASE_HOST=db
    restart: on-failure

    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - authors_volume:/var/lib/mysql


volumes:
  authors_volume:
